### ISSUE TITLE
Réparer la CI / contribuer

### ISSUE THREAD

**Issue by Shamzic** [betagouv/aides-jeunes#4388]
Simon : la PR https://github.com/betagouv/aides-jeunes/pull/4381 contribue à cette tâche
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/aides-jeunes/pull/4381
- [ ] https://github.com/betagouv/aides-jeunes/pull/4392
- [ ] Autres problèmes de version CI / contribuer
```

**Comment by Shamzic** [comment]
@jenovateurs Avais-tu rencontré d'autres problèmes que la version de node sur la CI ?
