### ISSUE TITLE
MAJ debian-v12

### ISSUE THREAD

**Issue by Shamzic** [betagouv/aides-jeunes#4467]
Passer à la nouvelle version LTS

- [x] Backup MongoDb #4538 
- [x] MAJ Ansible debian 11 to 12 #4536
- [x] MAJ manuel preprod en loggant les opérations #4585 
- [x] Tester l'environnement preprod avec la nouvelle version debian [4586](https://github.com/betagouv/aides-jeunes/issues/4586)
- [x] Potentiellement afficher un message prévenant de l'indisponibilité de la plateforme AJ le temps de la MAJ (non nécessaire car la période d'indisponibilité semble courte / weekly du 2/9/24)
- [x] Maj le serveur de prod  ( à faire en janvier)
- [x] Merge la branche Ansible debian 12 https://github.com/betagouv/aides-jeunes-ops/pull/193
